### ISSUE TITLE
Modernizing the mod

### ISSUE THREAD

**Issue by arphox** [Xebeth/StardewValley-ListModsCommand#1]
Hi!

Are you open for contributions?

I have found a bug and I'd also try to modernize the code to the current versions.

Or if you don't want to deal with it, you can maybe add me as a collaborator and I can continue the development of the mod, or I can fork it and redistribute it on your approval.

**Comment by Xebeth** [comment]
Invited as a contributor

**Comment by arphox** [comment]
@Xebeth 

> Invited as a contributor

Thank you!

One more thing: I can only publish updates to the mod on the Nexus site if you add me there too, could you do that too, please?

Steps:
1. Go here: https://www.nexusmods.com/stardewvalley/mods/edit/?step=permissions&id=5131
2. Add me as an editor
![kép](https://user-images.githubusercontent.com/17320094/226465378-24c84c76-e4f2-4ae4-b250-f14bd46eb204.png)

**Comment by Xebeth** [comment]
Done 👍🏻
